### ISSUE TITLE
LaTeX Support for Labels (Title, Axes, Ticks, Colorbar, etc.)

### ISSUE THREAD

**Issue by cdeciampa** [holoviz/holoviews#5740] opened 2023-06-04 22:27 UTC
Package versions:
- holoviews = 1.16.1
- datashader = 0.15.0
- bokeh = 3.1.1

As of Bokeh 3.0, [LaTeX is now supported](https://docs.bokeh.org/en/3.1.1/docs/user_guide/styling/mathtext.html), but I don't think it's supported by holoviews yet. Using `r"Upwelling Longwave Flux W$$m^{-2}$$"` doesn't work for the colorbar label:

![test_olr](https://github.com/holoviz/holoviews/assets/66640080/f7ca8079-2af0-41c3-b4aa-de3bb6ecc3a0)

And using that same label but for the title throws a KeyError:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[28], line 1
----> 1 hv.save(mpas_raster_plot, '../figs/test_olr.png', dpi=300, center=False)

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/holoviews/util/__init__.py:807, in save(obj, filename, fmt, backend, resources, toolbar, title, **kwargs)
    805     if formats[-1] in supported:
    806         filename = '.'.join(formats[:-1])
--> 807 return renderer_obj.save(obj, filename, fmt=fmt, resources=resources,
    808                          title=title)

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/holoviews/plotting/renderer.py:594, in Renderer.save(self_or_cls, obj, basename, fmt, key, info, options, resources, title, **kwargs)
    592         if fmt in MIME_TYPES:
    593             basename = '.'.join([basename, fmt])
--> 594     plot.layout.save(basename, embed=True, resources=resources, title=title)
    595     return
    597 rendered = self_or_cls(plot, fmt)

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/panel/viewable.py:985, in Viewable.save(self, filename, title, resources, template, template_variables, embed, max_states, max_opts, embed_json, json_prefix, save_path, load_path, progress, embed_states, as_png, **kwargs)
    939 def save(
    940     self, filename: str | os.PathLike | IO, title: Optional[str] = None,
    941     resources: Resources | None = None, template: str | Template | None = None,
   (...)
    946     as_png: bool | None = None, **kwargs
    947 ) -> None:
    948     """
    949     Saves Panel objects to file.
    950 
   (...)
    983       string and ends with png.
    984     """
--> 985     return save(
    986         self, filename, title, resources, template,
    987         template_variables, embed, max_states, max_opts,
    988         embed_json, json_prefix, save_path, load_path, progress,
    989         embed_states, as_png, **kwargs
    990     )

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/panel/io/save.py:260, in save(panel, filename, title, resources, template, template_variables, embed, max_states, max_opts, embed_json, json_prefix, save_path, load_path, progress, embed_states, as_png, **kwargs)
    258     model = doc
    259 else:
--> 260     model = panel.get_root(doc, comm)
    261     if embed:
    262         embed_state(
    263             panel, model, doc, max_states, max_opts, embed_json,
    264             json_prefix, save_path, load_path, progress, embed_states
    265         )

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/panel/layout/base.py:286, in Panel.get_root(self, doc, comm, preprocess)
    282 def get_root(
    283     self, doc: Optional[Document] = None, comm: Optional[Comm] = None,
    284     preprocess: bool = True
    285 ) -> Model:
--> 286     root = super().get_root(doc, comm, preprocess)
    287     # ALERT: Find a better way to handle this
    288     if hasattr(root, 'styles') and 'overflow-x' in root.styles:

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/panel/viewable.py:658, in Renderable.get_root(self, doc, comm, preprocess)
    656 wrapper = self._design._wrapper(self)
    657 if wrapper is self:
--> 658     root = self._get_model(doc, comm=comm)
    659     if preprocess:
    660         self._preprocess(root)

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/panel/layout/base.py:170, in Panel._get_model(self, doc, root, parent, comm)
    168 root = root or model
    169 self._models[root.ref['id']] = (model, parent)
--> 170 objects, _ = self._get_objects(model, [], doc, root, comm)
    171 props = self._get_properties(doc)
    172 props[self._property_mapping['objects']] = objects

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/panel/layout/base.py:155, in Panel._get_objects(self, model, old_objects, doc, root, comm)
    153 else:
    154     try:
--> 155         child = pane._get_model(doc, root, model, comm)
    156     except RerenderError:
    157         return self._get_objects(model, current_objects[:i], doc, root, comm)

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/panel/pane/holoviews.py:380, in HoloViews._get_model(self, doc, root, parent, comm)
    378     plot = self.object
    379 else:
--> 380     plot = self._render(doc, comm, root)
    382 plot.pane = self
    383 backend = plot.renderer.backend

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/panel/pane/holoviews.py:461, in HoloViews._render(self, doc, comm, root)
    458     if comm:
    459         kwargs['comm'] = comm
--> 461 return renderer.get_plot(self.object, **kwargs)

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/holoviews/plotting/bokeh/renderer.py:70, in BokehRenderer.get_plot(self_or_cls, obj, doc, renderer, **kwargs)
     63 @bothmethod
     64 def get_plot(self_or_cls, obj, doc=None, renderer=None, **kwargs):
     65     """
     66     Given a HoloViews Viewable return a corresponding plot instance.
     67     Allows supplying a document attach the plot to, useful when
     68     combining the bokeh model with another plot.
     69     """
---> 70     plot = super().get_plot(obj, doc, renderer, **kwargs)
     71     if plot.document is None:
     72         plot.document = Document() if self_or_cls.notebook_context else curdoc()

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/holoviews/plotting/renderer.py:241, in Renderer.get_plot(self_or_cls, obj, doc, renderer, comm, **kwargs)
    238     defaults = [kd.default for kd in plot.dimensions]
    239     init_key = tuple(v if d is None else d for v, d in
    240                      zip(plot.keys[0], defaults))
--> 241     plot.update(init_key)
    242 else:
    243     plot = obj

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/holoviews/plotting/plot.py:936, in DimensionedPlot.update(self, key)
    934 def update(self, key):
    935     if len(self) == 1 and ((key == 0) or (key == self.keys[0])) and not self.drawn:
--> 936         return self.initialize_plot()
    937     item = self.__getitem__(key)
    938     self.traverse(lambda x: setattr(x, '_updated', True))

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/geoviews/plotting/bokeh/plot.py:106, in GeoPlot.initialize_plot(self, ranges, plot, plots, source)
    104 def initialize_plot(self, ranges=None, plot=None, plots=None, source=None):
    105     opts = {} if isinstance(self, HvOverlayPlot) else {'source': source}
--> 106     fig = super().initialize_plot(ranges, plot, plots, **opts)
    107     if self.geographic and self.show_bounds and not self.overlaid:
    108         from . import GeoShapePlot

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/holoviews/plotting/bokeh/element.py:2493, in OverlayPlot.initialize_plot(self, ranges, plot, plots)
   2491 self.tabs = self.tabs or any(isinstance(sp, TablePlot) for sp in self.subplots.values())
   2492 if plot is None and not self.tabs and not self.batched:
-> 2493     plot = self._init_plot(key, element, ranges=ranges, plots=plots)
   2494     self._init_axes(plot)
   2495 self.handles['plot'] = plot

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/holoviews/plotting/bokeh/element.py:498, in ElementPlot._init_plot(self, key, element, plots, ranges)
    495     properties['outline_line_alpha'] = 0
    497 if self.show_title and self.adjoined is None:
--> 498     title = self._format_title(key, separator=' ')
    499 else:
    500     title = ''

File /storage/work/c/cnd5285/mambaforge/envs/uviz/lib/python3.9/site-packages/holoviews/plotting/plot.py:490, in DimensionedPlot._format_title(self, key, dimensions, separator)
    486 def _format_title(self, key, dimensions=True, separator='\n'):
    487     label, group, type_name, dim_title = self._format_title_components(
    488         key, dimensions=True, separator='\n'
    489     )
--> 490     title = util.bytes_to_unicode(self.title).format(
    491         label=util.bytes_to_unicode(label),
    492         group=util.bytes_to_unicode(group),
    493         type=type_name,
    494         dimensions=dim_title
    495     )
    496     return title.strip(' \n')

KeyError: '-2'
```

**Comment by ianthomas23** [comment] 2023-06-05 10:31
A couple of observations:

1. LaTeX support in Bokeh for ColorBars has only recently been committed and is not in a release yet. It will be in 3.2 which should be released soon.
2. LaTeX support in Bokeh is limited to whole strings not substrings. Here is the simplest example working with bokeh 3.1.1 and holoviews 1.16.1:

<img width="930" alt="Screenshot 2023-06-05 at 11 23 37" 
src="https://github.com/holoviz/holoviews/assets/580326/281c6888-2d43-40f9-9b18-f2cde1094460">

The LaTeX substring issue is known and something we would like to fix, but I don't know if anyone is activately working on it.

I should also point out that when I first ran my simple example above I didn't see any LaTeX at all and I was seeing `DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0` errors in the javascript console which are related to https://github.com/bokeh/bokeh/issues/13139#issuecomment-1553315243. But now, with a cleanly installed conda environment I cannot reproduce those errors.

**Comment by cdeciampa** [comment] 2023-06-05 11:09
Ah, okay, I didn't realize about 1., the documentation is a little confusing because further down the page, there's an example using a substring with div and paragraph widgets. 

As for reproducing my error (which I think is what you meant), I didn't post a snippet of my code because I can't really share a condensed version. My research involves visualizing unstructured grid climate models (models that use unusual shapes as their grid, quasi-hexagons are shown above) and I use spatialpandas and holoviews.Polygons that have been rasterized with datashader. Since all of the packages within holoviews are managed separately, my error could be related to holoviews' interaction with a different package that's not obvious within the traceback.

**Comment by cdeciampa** [comment] 2023-06-05 16:33
I somehow missed you explaining earlier that whole strings of LaTeX are already supported for titles and axes labels in the current version of holoviews. Using the same string you have for the title, `r"$$\alpha \beta$$"`, I now get a different warning/error from bokeh specifically and the title doesn't plot:

`WARNING:bokeh.io.export:The webdriver raised a TimeoutException while waiting for a 'bokeh:idle' event to signify that the layout has rendered. Something may have gone wrong.`

![test_olr-2](https://github.com/holoviz/holoviews/assets/66640080/97dd6402-e382-426b-83a0-01a6604eba48)

Here's the smallest snippet of my code I could manage and what the spatialpandas dataframe looks like:

<img width="443" alt="Screenshot 2023-06-05 at 12 28 55 PM" src="https://github.com/holoviz/holoviews/assets/66640080/c01ffe34-2ac7-4af9-af6d-081160c99b31">

```
# Plots polygons
hv_polys = hv.Polygons(ian_df, vdims=['faces']).opts(color='faces')

# Declares spatial plotting bounds
x_range = tuple((-90, -72.5))
y_range = tuple((20, 32.5))

# Sets Datashader options
datashader_kw = dict(aggregator='mean', precompute=True, 
                     x_range=x_range, y_range=y_range, pixel_ratio=10)

# Rasterizes polygons
raster_plot = hv.operation.datashader.rasterize(hv_polys, **datashader_kw) 

# Sets additional plotting options
font_opts = dict(fontsize=dict(title='35pt', clabel='50pt', cticks='40pt'))
cbar_opts = dict(height=40, border_line_width=3)
cmap_opts = dict(cmap=flut_cmap, clim=(cmin, cmax), colorbar=True, colorbar_position='bottom', 
                 clabel='Upwelling Longwave Flux [W/m^2]')
plot_kw = dict(width=w, height=h, xaxis=None, yaxis=None, title=r"$$\alpha \beta$$", 
               colorbar_opts=cbar_opts, **cmap_opts, **font_opts)

# Adds additional options to rasterized plot
out_plot = raster_plot.opts(**plot_kw)

# Sets up geoviews layer
coastline_kw = dict(scale='10m', line_color='#FFFFFF', line_width=2.0, width=w, height=h)
coastline_layer = gf.coastline(projection=ccrs.PlateCarree()).opts(**coastline_kw, xlim=x_range, ylim=y_range)

# Updates plot with geoviews layer
out_plot = out_plot * coastline_layer

# Outputs plot
hv.save(out_plot, '../figs/test_olr.png', dpi=300, center=False)
```

**Comment by byquip** [comment] 2023-06-23 20:31
There seems to be bug with `RadioButtonGroup` labels. I tried to use Latex in one of the labels:
```python
lab = r"$$\text{Dependency on }R_{core}$$"
cbg_dif_loss_depend = RadioButtonGroup(labels=['Dependency on N', lab],active=1)
```
And result:

![image](https://github.com/holoviz/holoviews/assets/60094563/a0c50939-311b-4654-aa56-d6c79c8b6585)

**Comment by Hoxbro** [comment] 2023-06-24 08:42
@byquip please open an issue on [Bokeh issue tracker](https://github.com/bokeh/bokeh/issues) if an existing issue do not already exists. 

``` python
from bokeh.io import show, output_notebook
from bokeh.models import CustomJS, RadioButtonGroup

output_notebook()

lab = r"$$\text{Dependency on }R_{core}$$"
rbg = RadioButtonGroup(labels=['Dependency on N', lab],active=1)

show(rbg)
```
![image](https://github.com/holoviz/holoviews/assets/19758978/58cb19db-b03d-4555-a7fb-bad88802817f)

**Comment by wen-jams** [comment] 2023-08-04 04:04
Hello, I've encountered a similar issue with Latex labels, where they won't even show up. Following @ianthomas23 simple example, I get this:
![image](https://github.com/holoviz/holoviews/assets/40677090/bf170e29-1a2e-4227-af99-df79aaad3681)

Software versions:
holoviews 1.17.0
bokeh 3.2.1
jupyterlab 3.6.3
jupyter_bokeh 3.0.7

**Comment by sunilkpai** [comment] 2023-09-04 14:34
For some reason, mathjax appears to not be added to the templates in the HTML. I saved my plot as a standalone HTML and got this problem. The default template loading list appears to have changed in recent Bokeh versions to:

```
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-3.2.2.min.js"></script>
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-gl-3.2.2.min.js"></script>
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.2.2.min.js"></script>
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.2.2.min.js"></script>
```

which does not include mathjax.

So I needed to add

```
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-mathjax-3.2.2.min.js"></script>
```

Not sure how to make this the default for HTMLs generated in a notebook though. Any tips?

Software versions:
```
holoviews 1.17.1
bokeh 3.2.2
jupyterlab 4.0.5
jupyter_bokeh 3.0.7
```

**Comment by Hoxbro** [comment] 2023-10-11 16:17
The original problem by @cdeciampa, as far as I can see, is already supported or will need work done in Bokeh itself.

The second problem by @cdeciampa around `hv.save` not working needs a [minimal, reproducible example (MRE)](https://stackoverflow.com/help/minimal-reproducible-example) for me to be able to investigate. Please open a new issue if it is still a problem.

The problem by @ @byquip is a Bokeh feature request and is tracked on their issue tracker. 

The problem described by @wen-jams and @sunilkpai should be fixed by #5904 and will be out in the next release, 1.18. Thank you for the investigation, @sunilkpai. I really, really appreciated it!

I think that was all of it and if not please open new issues.

**Comment by wen-jams** [comment] 2023-10-31 20:40
@Hoxbro it seems like the fix in 1.18.0 is only working when running in `panel serve` and not for notebooks.

```python
import holoviews as hv
import panel as pn

hv.extension("bokeh", enable_mathjax=True)

a = hv.Rectangles([[0, 0, 1, 1]]).opts(title=r"$$\alpha \beta$$", xlabel="$$y$$")

pn.panel(a).servable()
```
For example in Jupyterlab with the Panel preview, you can see the LaTeX is rendered in the widget but not inline:
![image](https://github.com/holoviz/holoviews/assets/40677090/5f3a965b-7784-420b-8692-1f76048929a9)

The `pn.extension("mathjax")` fix suggested by @sunilkpai didn't work for me, either.

However, saving the plot to HTML shows that mathjax is indeed included:

```html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-3.3.0.min.js"></script>
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-gl-3.3.0.min.js"></script>
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.3.0.min.js"></script>
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.3.0.min.js"></script>
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-mathjax-3.3.0.min.js"></script>
<script type="text/javascript" src="https://cdn.holoviz.org/panel/1.3.0/dist/panel.min.js"></script>
```
The LaTeX labels show up fine in the plot from HTML as well.

Software versions:

```
holoviews 1.18.0
bokeh 3.3.0
panel 1.3.0
jupyterlab 4.0.7
jupyter_bokeh 3.0.7
```

**Comment by Hoxbro** [comment] 2023-11-02 09:22
I think this is an upstream issue, as I also see the same problem using Bokeh: https://github.com/bokeh/bokeh/issues/13499

**Comment by jbednar** [comment] 2024-12-03 22:19
Pure bokeh=3.3.4 seems to work for me, as does holoviews=1.18.3 with a Matplotlib backend, but holoviews=1.18.3 with a bokeh=3.3.4 backend does not:

```python
import numpy as np
from bokeh.plotting import figure, show

N = 4000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = np.array([(r, g, 150) for r, g in zip(50+2*x, 30+2*y)], dtype="uint8")

p = figure(width=300, height=300)
p.circle(x, y, radius=radii, fill_color=colors, fill_alpha=0.6, line_color=None)

p.xaxis.axis_label = r'$$\text{ This works } \times 10^6$$'

show(p)
```
![Image](https://github.com/user-attachments/assets/8cc63134-4576-4554-879d-733ba3dd4017)

```python
import pandas as pd, numpy as np, holoviews as hv
hv.extension("matplotlib")

x = np.linspace(start=0, stop=100000, num=25)
y = np.linspace(start=0, stop=35, num=25)
df_test = pd.DataFrame({'x':x, 'y': y, 'x2':x/10000})
hv.Points(df_test, ['x2', 'y']).opts(xlabel=r'$\text{ This works } \times 10^6$')
```
![Image](https://github.com/user-attachments/assets/01394a7c-8918-4b2c-98c5-3037628a8432)

```python
import pandas as pd, numpy as np, holoviews as hv
hv.extension("bokeh")

x = np.linspace(start=0, stop=100000, num=25)
y = np.linspace(start=0, stop=35, num=25)
df_test = pd.DataFrame({'x':x, 'y': y, 'x2':x/10000})
hv.Points(df_test, ['x2', 'y']).opts(xlabel=r'$\text{ This is messed up } \times 10^6$')
```
![Image](https://github.com/user-attachments/assets/f76d060b-8edc-40a4-b885-856e9bcf6d09)

```python
import pandas as pd, numpy as np, holoviews as hv
hv.extension("bokeh")

x = np.linspace(start=0, stop=100000, num=25)
y = np.linspace(start=0, stop=35, num=25)
df_test = pd.DataFrame({'x':x, 'y': y, 'x2':x/10000})
hv.Points(df_test, ['x2', 'y']).opts(xlabel=r'$$\text{ This is messed up } \times 10^6$$')
```
![Image](https://github.com/user-attachments/assets/20390755-b1cc-4d91-bf29-38522920af53)

(i.e. a single `$` works with the matplotlib backend, but with Bokeh it prints the literal text, and using `$$` with Bokeh shows nothing at all.)

**Comment by hoxbro** [comment] 2024-12-04 10:18
You are not using the latest versions of Bokeh (3.6.2) or HoloViews (1.20.0). I have pasted the results in for those below. The single `$` sign is [MathJax default delimiters](http://docs.mathjax.org/en/latest/basic/mathematics.html#tex-and-latex-input), and is those used by [Bokeh](https://docs.bokeh.org/en/latest/docs/user_guide/styling/mathtext.html#latex). 

<details>
<summary>Bokeh Code</summary>

``` python
import numpy as np
from bokeh.io import output_notebook
from bokeh.plotting import figure, show

output_notebook()
N = 4000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = np.array([(r, g, 150) for r, g in zip(50 + 2 * x, 30 + 2 * y)], dtype="uint8")

p = figure(width=300, height=300)
p.circle(x, y, radius=radii, fill_color=colors, fill_alpha=0.6, line_color=None)

p.xaxis.axis_label = r"$$ \text{ This works } \times 10^6$$"

show(p)
```

</details>
 
![Image](https://github.com/user-attachments/assets/19f52552-27d1-4246-b69a-f964ead7b89c)

<details>
<summary>HoloViews Code</summary>

``` python
import numpy as np
import pandas as pd

import holoviews as hv

hv.extension("bokeh")

x = np.linspace(start=0, stop=100000, num=25)
y = np.linspace(start=0, stop=35, num=25)
df_test = pd.DataFrame({"x": x, "y": y, "x2": x / 10000})
hv.Points(df_test, ["x2", "y"]).opts(
    xlabel=r"$$\text{ This is messed up } \times 10^6$$"
)
```

</details>

![Image](https://github.com/user-attachments/assets/5768569d-b668-498f-af2c-b38915d6b062)


Note that the problem reported by @wen-jams has also been fixed upstream. So, I will close the issue. 

![Image](https://github.com/user-attachments/assets/408f65be-e266-40ce-9bf1-59dce51c1881)

**Closed by hoxbro** 2024-12-04 10:18 UTC

**Comment by michaelaye** [comment] 2024-12-15 17:28
note that Bokeh 3.6.2 clashes with geoviews 1.13.0, mamba needs it to downgrade it to 1.8.2 apparently, so I can't get to that new Bokeh to make my labels work. :/ I guess this is a feature request for the geoviews tracker?

<img width="620" alt="Image" src="https://github.com/user-attachments/assets/e94d50a7-869b-4d8c-8cea-2bbc638eef20" />

**Comment by hoxbro** [comment] 2024-12-16 13:37
> I guess this is a feature request for the geoviews tracker?

Correct. I have made an RC release for GeoViews with Bokeh 3.6 support and will make an official release tomorrow or Wednesday.

**Comment by gVallverdu** [comment] 2025-03-04 09:41
@hoxbro Using up to date version of bokeh and holoviews work in standard jupyter(-lab) but you need to install also `jupyter_bokeh`.

However, using the same python environment, it does not work if I use jupyter in visual studio code.

I tried with or without the `show()` function of bokeh and the result is the same.

<img width="787" alt="Image" src="https://github.com/user-attachments/assets/ccec7be8-5876-4a9a-a1de-f37e33328235" />

Pure bokek doesn't work neither

<img width="751" alt="Image" src="https://github.com/user-attachments/assets/e60ab4f6-06c1-4b01-803d-12d01292aa8b" />
