### ISSUE TITLE
VSpan links axes in vertical layout

### ISSUE THREAD

**Issue by erezinman** [holoviz/holoviews#4398] opened 2020-04-26 19:26 UTC
Hi, 
It appears that adding a VSpan to the layout links the y-axis of the plots. Is it possible to disable this behavior? Alternatively, is there any other class that I can use mark intervals without linking the y-axes?

Thanks in advance

MWE:
![image](https://user-images.githubusercontent.com/4324329/80317494-c851a380-880c-11ea-960b-d3032c7ada11.png)

![image](https://user-images.githubusercontent.com/4324329/80317523-0222aa00-880d-11ea-96d0-e8687effc4a0.png)

**Comment by philippjfr** [comment] 2020-04-26 19:40
You can add`.opts(opt.VSpan(axiswise=True))` but I'll consider this a bug. Unless `apply_ranges` is set I don't think linking should happen in this case.

**Comment by philippjfr** [comment] 2020-04-26 19:41
Actually I'm not sure `axiswise=True` will work, you may also have to set the `VSpan` vdim.

**Comment by erezinman** [comment] 2020-04-26 20:42
Tried both before I posted, but couldn't get it to work.

**Comment by AurelienSciarra** [comment] 2020-08-14 07:16
For me it's not a bug. In order to unlink the y-axes you just need to invert your curve and your VSpan in your overlay.

Maybe I'm wrong but I think it works that  way :
When making an overlay, holoviews takes the dim of the first object and then change their values according to the other plot.
In that case, It took the dim of the Vspan which names are 'x' and 'y' by default then it change the values. So both curve have the same dim names. And by default hv.Layout links all axes with the same dim name.

The solution is to invert the VSpan and the Curve like that :

`x = np.arrange(0,1000)/1000*2*np.pi
curve_1 = hv.Curve((x,np.sin(x)),'x',('y1','y'))*hv.VSpan(1,2)
curve_2 = hv.Curve((x,2*np.sin(x)),'x',('y2','y'))*hv.VSpan(1,2)

hv.Layout([curve_1,curve_2])`

Correct me if I'm wrong and maybe this was fixed in the last release without  being added to the release note.

**Closed** 2020-09-01 21:30 UTC
Labels: type: bug
