### ISSUE TITLE
Bars Element does not color bars according to a categorical DataFrame column with Bokeh

### ISSUE THREAD

**Issue by TizianoGC** [holoviz/holoviews#4457] opened 2020-06-07 15:36 UTC
#### ALL software version info
_conda environment_
python                    3.7.6           h8356626_5_cpython    conda-forge
bokeh                     2.0.1            py37hc8dfbb8_0    conda-forge
holoviews                 1.13.2             pyh9f0ad1d_0    conda-forge
hvplot                    0.5.2                      py_0    conda-forge
_OS_
Ubuntu 18.04

#### Description of expected behavior and the observed behavior
I would like to colour a bar plot according to the categories in a DataFrame column, but the bars have the same colour.

#### Complete, minimal, self-contained example code that reproduces the issue
Test DataFrame in file "test.csv"
name,count,fam
cheese,5,fam1
apple,3,fam2
pears,1,fam2
bread,4,fam3
```
import pandas as pd
import holoviews as hv
from holoviews import opts

hv.extension('bokeh')

df = pd.read_csv('test.csv')
p = hv.Bars(df, 'name', ['count','fam']).opts(opts.Bars(color='fam'))
hv.save(p, 'test.html')
```
#### Screenshots or screencasts of the bug in action
![barplot](https://user-images.githubusercontent.com/11617713/83973154-70fb2480-a8dc-11ea-9223-a9609038f68d.png)

Could you please fix it? Many thanks!

**Comment by philippjfr** [comment] 2020-06-07 17:04
Thanks for filing this issue. You can fix this yourself by providing a categorical colormap, e.g. 

```python
p = hv.Bars(df, 'name', ['count','fam']).opts(color='fam', cmap='Category10')
```

Otherwise this is a duplicate of #4200.

**Closed by philippjfr** 2020-06-07 17:04 UTC

**Comment by mullimanko** [comment] 2021-01-27 09:22
How can I do this with matplotlib backend? There is no `cmap` option.
