### ISSUE TITLE
obs_density KeyError with KDE HoloMap

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#3060] opened 2018-10-08 17:50 UTC
```
tst = pd.DataFrame({'obs': [0, 1, 2], 'mod': [3, 4, 5]})
hmap_dict = {'Item1': ((tst.hvplot('obs', label='Mean') * tst.hvplot.area('obs', label='Range') + tst.hvplot.kde('obs')).relabel('AnOverlay')).regroup('Group1').cols(2),
             'Item2': ((tst.hvplot('mod', label='Mean') * tst.hvplot.area('mod', label='Range') + tst.hvplot.kde('mod')).relabel('AnOverlay')).regroup('Group2').cols(2)}

hv.HoloMap(hmap_dict, kdims='Items').collate()
```

```

~/holoviews/holoviews/plotting/bokeh/chart.py in get_extents(self, element, ranges, range_type)
    544             ranges[vdim] = new_range
    545         else:
--> 546             s0, s1 = ranges[vdim]['soft']
    547             s0 = min(s0, 0) if isfinite(s0) else 0
    548             s1 = max(s1, 0) if isfinite(s1) else 0

KeyError: 'obs_density'
```

If I remove the KDE plots, it runs, but it shows all the plots + a dropdown box as well

**Comment by philippjfr** [comment] 2018-10-08 18:07
Likely a regression since the padding PR was merged.

**Comment by philippjfr** [comment] 2018-10-09 01:35
Something going wrong with the different groups and labels there that's causing the ranges not to be populated correctly.

**Comment by philippjfr** [comment] 2020-06-08 13:43
Seems to have been fixed.

**Closed by philippjfr** 2020-06-08 13:43 UTC
Labels: regression
