### ISSUE TITLE
Error bars not working for categorical axis with bokeh

### ISSUE THREAD

**Issue by bstadlbauer** [holoviz/holoviews#4627] opened 2020-09-22 11:44 UTC
#### ALL software version info
holoviews = 1.13.3
python = 3.6.10
bokeh = 2.2.1 

on MacOs 10.14.6

#### Description of expected behavior and the observed behavior
Expected: Error bars are shown for categorical values

Error bars are not shown, issue should already be resolved: 
https://github.com/holoviz/holoviews/issues/1470

#### Complete, minimal, self-contained example code that reproduces the issue

```
%%opts ErrorBars (line_width=2 line_color='darkblue')
%%opts Points    [invert_axes=False] (color='darkred' size=6)
import holoviews as hv
import numpy as np

x=['a','b','c','d','e']
points = [(x[i], 5*np.random.rand()) for i in range(5)]
errors = [points[i]+(np.random.rand()/2,) for i in range(5)]

h1 = hv.Points(points)
h2 = hv.ErrorBars(errors)
h2*h1

```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/11799671/93877734-32497880-fcd9-11ea-99c0-c2057828242d.png)

**Comment by jlstevens** [comment] 2020-10-05 15:32
Based on the issue you linked to, this definitely sounds like a regression (since it looks like it was fixed in 2017!)

**Comment by kubekmonika** [comment] 2020-12-13 21:07
Hello, I have just stambled upon this error. Is there any workaround I can use before it is fixed?

**Comment by lgonzalezsa** [comment] 2021-01-26 02:22
Hola,
Seems to be related to categorical data in X axis; was facing the issue today and at the time I changed the X axis to numerical, the error bars start  working. Need to show the categorical values in the x axis; any suggestion for workaround more than welcome.

Look the new definition of `points `variable.
```
%%opts ErrorBars (line_width=2 line_color='darkblue')
%%opts Points    [invert_axes=False] (color='darkred' size=6)

x=['a','b','c','d','e']
points = [(i,5*np.random.rand()) for i in range(5)]
#[(x[i], 5*np.random.rand()) for i in range(5)]
errors = [points[i]+(np.random.rand()/2,) for i in range(5)]

h1 = hv.Points(points)
h2 = hv.ErrorBars(errors)
h2*h1
```

**Comment by philippjfr** [comment] 2021-02-09 17:29
Cannot reproduce any issues with this in latest HoloViews. @jlstevens Can you reprodduce?

**Comment by philippjfr** [comment] 2021-02-09 17:59
Okay, now have multiple confirmations that this cannot be reproduced with latest versions. Closing.

**Comment by jlstevens** [comment] 2021-02-09 17:59
I can't seem to reproduce this either:

![image](https://user-images.githubusercontent.com/890576/107406646-4813da80-6ace-11eb-81ad-bd6e3c3118a4.png)

**Closed by philippjfr** 2021-02-09 17:59 UTC
Labels: type: bug

**Comment by lgonzalezsa** [comment] 2021-02-10 02:41
Am using 1.14.1 and still not able to get the error bars.
What am missing here?

![image](https://user-images.githubusercontent.com/704686/107457151-28ed6b00-6b17-11eb-91ba-5466dafebf66.png)

**Comment by philippjfr** [comment] 2021-02-10 02:44
We are testing against master. It may also come down to the Bokeh version though. In any case there will be new HoloViews and Bokeh releases very soon.

**Comment by lgonzalezsa** [comment] 2021-02-10 19:16
Thanks a lot @philippjfr that clarifies. Thank you for the great work!

**Comment by philippjfr** [comment] 2021-02-10 19:18
Release timeline is now pushed to next week.
