### ISSUE TITLE
hv.Distribution label cannot contain a period

### ISSUE THREAD

**Issue by matt-erhart** [holoviz/holoviews#4062] opened 2019-10-16 18:49 UTC
```python
hv.Distribution(
            actual_error,label='7.5', group='KDE'
        ).opts(bandwidth=0.15)
# results in key error '7'
```

```python
hv.Distribution(
            actual_error,label='75.', group='KDE'
        ).opts(bandwidth=0.15)
# results in key error '75'
```

**Comment by philippjfr** [comment] 2019-10-16 20:46
Tbh, I think this is true for all elements. A workaround is to set `.opts(title_format='0.75')`.

**Comment by philippjfr** [comment] 2020-01-06 14:47
In fact this is a duplicate of https://github.com/holoviz/holoviews/issues/2090

**Closed by philippjfr** 2020-01-06 14:47 UTC
