### ISSUE TITLE
FreehandDraw on no empty Path raises ValueError.

### ISSUE THREAD

**Issue by ruoyu0088** [holoviz/holoviews#4538] opened 2020-07-30 05:15 UTC
Here is the code:

```python
import holoviews as hv
from holoviews import opts, streams
hv.extension('bokeh')

path = hv.Path(([1, 1], [2, 2]))
freehand = streams.FreehandDraw(source=path, num_objects=3,
                                styles={'line_color': ['red', 'green', 'blue']})

path.opts(
    opts.Path(active_tools=['freehand_draw'], height=400, line_width=10, width=400))
```

After draw a path with mouse, the following exception rasied:

```
Traceback (most recent call last):
  File "c:\Miniconda3_64bit\lib\site-packages\pyviz_comms\__init__.py", line 316, in _handle_msg
    self._on_msg(msg)
  File "c:\Miniconda3_64bit\lib\site-packages\holoviews\plotting\bokeh\callbacks.py", line 144, in on_msg
    processed_msg = self._process_msg(filtered_msg)
  File "c:\Miniconda3_64bit\lib\site-packages\holoviews\plotting\bokeh\callbacks.py", line 1165, in _process_msg
    vals = sorted([(int(k), v) for k, v in vals.items()])
  File "c:\Miniconda3_64bit\lib\site-packages\holoviews\plotting\bokeh\callbacks.py", line 1165, in <listcomp>
    vals = sorted([(int(k), v) for k, v in vals.items()])
ValueError: invalid literal for int() with base 10: 'dtype'
```

The message passed to `on_msg()` is as following:

```
{'header': {'date': datetime.datetime(2020, 7, 30, 5, 30, 34, 321000, tzinfo=tzutc()),
  'msg_id': '37c97073-230e-427d-a54f-5d2b2e39f078',
  'msg_type': 'comm_msg',
  'session': '3cc0ee33-6c0c-4af3-90a0-89beeeb0c284',
  'username': '',
  'version': '5.2'},
 'msg_id': '37c97073-230e-427d-a54f-5d2b2e39f078',
 'msg_type': 'comm_msg',
 'parent_header': {},
 'metadata': {},
 'content': {'comm_id': 'c8a10577-3305-4268-a66b-5918e6335c3e',
  'data': {'data': {'id': '1034',
    'value': {'line_color': ['red', 'green'],
     'xs': [{'0': 1, '1': 1, 'dtype': 'int32', 'shape': [2]},
      [0.47826086956521746,
       0.28447204968944106,
       0.23229813664596277,
       0.2024844720496895,
       0.2024844720496895,
       0.2024844720496895,
       0.2099378881987578,
       0.3888198757763976,
       0.48571428571428577,
       0.8285714285714286,
       0.9105590062111802,
       0.9925465838509319,
       0.9925465838509319,
       0.9925465838509319]],
     'ys': [{'0': 2, '1': 2, 'dtype': 'int32', 'shape': [2]},
      [1.2208695652173915,
       1.464347826086957,
       1.6730434782608699,
       1.9234782608695655,
       1.979130434782609,
       2.1321739130434785,
       2.1460869565217395,
       2.201739130434783,
       2.2226086956521742,
       2.229565217391305,
       2.229565217391305,
       2.229565217391305,
       2.229565217391305,
       2.229565217391305]]}},
   'comm_id': '4f5d4494aebb4440a102dbafe73af5a2'}},
 'buffers': []}
```

the first element of `xs` data is a dict, the second is a list. the `_process_msg()` method of `CDSCallback` cannot process this kind of data:

https://github.com/holoviz/holoviews/blob/7c95788c07ede09c8a8e26b4ac4bbfd0dd9a82a9/holoviews/plotting/bokeh/callbacks.py#L1132

**Comment by philippjfr** [comment] 2020-08-29 21:27
This was a regression caused by bokeh 2.1.1 which was fixed in recent 1.13.3. Sadly bokeh 2.2 caused another such regression so we will have to release 1.13.4 soon for compatibility.

**Closed by philippjfr** 2020-08-29 21:27 UTC
