### ISSUE TITLE
Backend-specific option ignored

### ISSUE THREAD

**Issue by douglas-raillard-arm** [holoviz/holoviews#4962] opened 2021-06-02 11:35 UTC
#### ALL software version info
holoviews: 1.14.3
matplotlib: 3.4.2
bokeh: 2.3.2

#### Description of expected behavior and the observed behavior
Disclaimer: I'm a new user and I had to dive straight pretty deep to support my use case, API misuse is not unlikely.

When setting backend-specific options for a non-default backend, the calls to options() seem to override each-other.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
backend = 'bokeh'
# If the backend that is actually used is the default (i.e. bokeh), the bug disappears
hv.extension('matplotlib', 'bokeh')
print(hv.Store.current_backend)

# The 2nd options() call seems to override the first one
x = hv.Curve([1,2,3]).options(interpolation='steps-pre', backend=backend).options(color='red', backend=backend)
hv.output(x, backend=backend)

# When setting both options at once, the bug disappears
x = hv.Curve([1,2,3]).options(interpolation='steps-pre', color='red', backend=backend)
hv.output(x, backend=backend)
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/23336875/120473463-f229b200-c39e-11eb-9333-6fabe061217d.png)

**Comment by jbednar** [comment] 2021-06-02 14:56
I can reproduce, both with .options and with .opts.  That's very surprising!

**Comment by jlstevens** [comment] 2021-06-02 15:09
Agreed. Definitely looks like a bug.

**Comment by douglas-raillard-arm** [comment] 2021-06-02 16:06
It looks like changing the default backend with `hv.Store.set_current_backend(backend)` prior to constructing the holoviews elements provides a workaround. I wrapped it in a context manager:
```
                @contextlib.contextmanager
                def set_backend(backend):
                    old_backend = hv.Store.current_backend
                    try:
                        hv.Store.set_current_backend(backend)
                        yield
                    finally:
                        if old_backend:
                            hv.Store.set_current_backend(old_backend)
```

**Comment by jbednar** [comment] 2021-06-02 20:48
That's a good suggestion, and a useful bit of code I'd be happy to see in HoloViews itself (potential PR?).  I'd maybe call it just `backend` so that the usual context manager usage would read as `with backend("bokeh"):`. But the underlying issue should also be fixed in HoloViews itself.

**Closed** 2021-08-03 15:00 UTC
Labels: type: bug

**Comment by jbednar** [comment] 2021-08-03 18:08
Thanks, @philippjfr! I'd still be happy to see `with hv.backend("bokeh"):` appear...

**Comment by douglas-raillard-arm** [comment] 2021-08-05 09:03
@jbednar I'm happy to add that as well, which module should it live in ?

**Comment by jlstevens** [comment] 2021-08-05 09:13
I'm not sure how useful a context manager like this is in a notebook context: anything inside the context manager block won't automatically get displayed by the usual notebook machinery.

I have no objection to this idea but I would need to be shown some example use cases first to be convinced that it is useful.

**Comment by jbednar** [comment] 2021-08-05 15:52
Yes, it's very irritating that a context manager has no return value that Jupyter can display. In this case, though, the intent is to use the decorator to set options "in bulk", i.e. likely for a bunch of objects, none of which are expected to be displayed immediately. The intent is for pre-setting a bunch of things, because otherwise there would be no need to use this mechanism; anything immediately displayed would only need to be supported for one backend, not flexibly switching as this context manager focuses on.

**Comment by jlstevens** [comment] 2021-08-05 16:03
Ok, I wouldn't anticipate this being a common need but that doesn't mean it can't be supported.

**Comment by jlstevens** [comment] 2021-08-05 16:13
By the way, I think as option logic this should live together with `Store` in `core.options`. It can then be exposed at a higher level though I'm not entirely sold on that just yet.

**Comment by jlstevens** [comment] 2021-08-05 16:33
Actually, `Store` is exposed at the top level and I would be happy with this context manager living there:

```python
with hv.Store.backend('bokeh'):
   ...
```

**Comment by douglas-raillard-arm** [comment] 2021-08-05 22:10
This could probably be bundled with a way to temporarily override some global default options used when creating new plots, e.g.:
```
##### CODE IN A 3rd PARTY LIB #######

def lib_decorator(f):
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        # Overrides some options but otherwise inherits them from an outer
        # "with hv.Store.options" or the global options.
        with hv.Store.options(opts.Curve(color='red'), backend='bokeh'):
            return f(*args, **kwargs)
    return wrapper

@lib_decorator
def lib_func(ys):
    return hv.Curve(ys)


# It is even possible to use the context manager as a decorator using https://docs.python.org/3/library/contextlib.html#contextlib.ContextDecorator:
theme = hv.Store.options(opts.Curve(color='red'), backend='bokeh')

@theme
def lib_func(...):
    ....
#### USER NOTEBOOK ####

opts.defaults(opts.Curve(line_dash='dashed'))

# Displayed with color=red, line_dash=dashed
lib_func([0, 1])
```
This can allow people to create some sort of themes, while still letting through all the global defaults that the theme does not explicitly override. The code creating the plots themselves will still be able to override the defaults where it is really necessary for e.g. readability.

A library cannot currently apply its own "local defaults" without changing the user's global defaults. With context managers, it becomes possible to have an arbitrary number of theming layers rather than just one.

Note: there seems to be a StoreOptions.options() context manager but it looks like it is limited to operating on one object, rather than the whole global defaults.
