### ISSUE TITLE
legend_cols=int in bokeh

### ISSUE THREAD

**Issue by rchurt** [holoviz/holoviews#4529] opened 2020-07-23 03:13 UTC
I see [here](http://holoviews.org/user_guide/Customizing_Plots.html#Legend-customization) that users can put "...the legend elements in a column layout with `legend_cols=True` or (`legend_cols=int` in matplotlib)". Could you extend the `legend_cols=int` option to bokeh?

**Comment by philippjfr** [comment] 2020-07-23 10:29
Thanks for the issue. This would have to be implemented in Bokeh first, see https://github.com/bokeh/bokeh/issues/3880

**Comment by kidpixo** [comment] 2021-09-03 12:54
@rchurt In [element.py(L2059)](https://github.com/holoviz/holoviews/blob/b30b437baa14185cb37ea94cb4e485404725004c/holoviews/plotting/bokeh/element.py#L2059)  `legend_cols`  is only checked for  `True`, any other value result in a vertical legend.

```python 
plot.legend.orientation = 'horizontal' if self.legend_cols else 'vertical'
```

**Comment by maximlt** [comment] 2022-10-23 16:11
Duplicate of https://github.com/holoviz/holoviews/issues/3780

**Closed by maximlt** 2022-10-23 16:11 UTC
Labels: tag: backend: bokeh
