### ISSUE TITLE
Broken dynamic eq_hist Bokeh Datashader plots with colorbars

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviews#4978] opened 2021-06-17 02:06 UTC
At first I thought this was a Bokeh issue, but I haven't been able to reproduce it in a static export or by following [Bokeh examples](http://docs.bokeh.org/en/latest/docs/user_guide/annotations.html#color-bars), so I'm filing it here on HoloViews. Specifically, a Datashader plot with eq_hist and colorbars works fine if it's not dynamic:

```python
import dask.dataframe as dd, holoviews as hv
from holoviews.operation.datashader import rasterize, dynspread
import bokeh, datashader as ds
hv.extension("bokeh")

df = dd.read_parquet('data/nyc_taxi_wide.parq').compute()
pts = hv.Points(df, ['dropoff_x', 'dropoff_y'])
opts = hv.opts.Image(cnorm='eq_hist', colorbar=True, width=700)
ds.__version__, hv.__version__, bokeh.__version__
```

![image](https://user-images.githubusercontent.com/1695496/122318784-44152080-cee5-11eb-81ef-bf5040559a4f.png)

![image](https://user-images.githubusercontent.com/1695496/122319418-3a3fed00-cee6-11eb-9f93-2824e0d53e14.png)

but it fails if `dynamic=True`:

![image](https://user-images.githubusercontent.com/1695496/122318857-6149ef00-cee5-11eb-9669-4923b890325a.png)

Here the immediate symptom is that the colorbar labels are gone, but more seriously as soon as the user pans or drags, the plot flickers briefly into a massively zoomed in bit of the plot, roughly like:

![image](https://user-images.githubusercontent.com/1695496/122319619-71ae9980-cee6-11eb-9417-ac5aa9c77239.png)

then disappears altogether:

![image](https://user-images.githubusercontent.com/1695496/122318954-85a5cb80-cee5-11eb-9317-17522efea4ce.png)

After the plot disappears, the JS console shows:

![image](https://user-images.githubusercontent.com/1695496/122319072-b6860080-cee5-11eb-861e-2a91f9d6daaf.png)

It works fine if there is no colorbar or if `cnorm='log'`, so it seems like it's something to do with showing an eq_hist colorbar dynamically. I see the same behavior with bokeh 2.3.0, 2.3.1, and 2.3.2.

**Comment by jlstevens** [comment] 2021-06-17 10:33
Philipp's theory is that the colorbar labels are getting too long, blowing up the plot. I'll test that by seeing whether a custom formatter fixes it.

**Comment by jlstevens** [comment] 2021-06-17 15:28
After discussing this problem with @philippjfr and @mattpap, we conclude the following:

* This particular example can be addressed by setting `frame_width` and `frame_height` in the image opts and matching it to `width` and `height` in the operation call.
* The error seems to be in Bokeh when computing the bounding box (specifically in the y-dimension) of labels. This is a transient state when `dynamic=True` (without the set heights/widths) that gets bokeh into a broken state it can't get out of.

**Comment by philippjfr** [comment] 2021-06-17 16:29
@mattpap Here's the notebook I promised https://anaconda.org/philippjfr/broken_colorbar_labels/notebook

Click the button and you'll be able to reproduce the error and hopefully debug it.

**Comment by mattpap** [comment] 2021-06-17 17:04
The problem is with:
https://github.com/bokeh/bokeh/blob/e98b8b7907b7ad34fd39f0985a71cfcab811b8f0/bokehjs/src/lib/models/scales/linear_interpolation_scale.ts#L76-L82

```ts
      if (v < min_val)
        return min_val
      if (v > max_val)
        return max_val
      const k = left_edge_index(v, binning)
      const b0 = binning[k]
      const b1 = binning[k+1]
```
The offending value (40000) is equal to to `max_val`, which results in `k` being out of bounds and then `b0` and b1` being `undefined`, which later results in `NaN`. I'm presuming a quick fix is to replace `<` and `>` with `<=` and `>=`.

**Comment by jbednar** [comment] 2021-06-17 17:07
Thanks, @philippjfr, @jlstevens, and @mattpap! Sounds like a good theory, to me!

**Comment by philippjfr** [comment] 2021-06-17 17:09
Ah, great, it's my fault then 😆

**Comment by mattpap** [comment] 2021-06-17 17:21
I will submit a PR and target this for 2.3.3 together with layout regression fixes.

**Comment by philippjfr** [comment] 2021-11-16 11:43
This was fixed in bokeh.

**Closed by philippjfr** 2021-11-16 11:43 UTC
Labels: TRIAGE
