### ISSUE TITLE
Datashading a xarray/dask array hangs forever without calling `compute()`

### ISSUE THREAD

**Issue by phildong** [holoviz/holoviews#4331] opened 2020-03-28 16:20 UTC
When datashading an image constructed from a xarray with dask backend, it seems I always have to manually call the `compute()` on the array before feeding it into holoviews. The operation seem to hang forever at a given percentage (visualized by dask progress bar) if the raw xarray/dask array was feed into holoviews.

I understand this might not be a pure holoviews issue as it involves several other libraries, however it seems holoviews are supposed to play well with them under this circumstances. Any suggestions/directions on this would be helpful!

#### ALL software version info
holoviews: 1.12.7
dask: 2.11.0
xarray: 0.15.0
python: 3.8.1
OS: ubuntu 18.04.1

#### Description of expected behavior and the observed behavior

I expect holoviews/datashader to handle dask array well without explicitly converting them into "in memory" arrays using `compute()`. However it seems the operation hangs without the `compute()`.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import numpy as np
import xarray as xr
import holoviews as hv
import dask.array as da
from dask.diagnostics import ProgressBar
from holoviews.operation.datashader import datashade, regrid

hv.notebook_extension('bokeh')
pbar = ProgressBar(minimum=2)
pbar.register()

arr = xr.DataArray(np.random.random((1000, 1000))).chunk(100)

datashade(hv.Image(arr.compute())) # this returned the proper plot instantly
datashade(hv.Image(arr)) # this hangs at certain percentage indefinitely
regrid(hv.Image(arr)) # this hangs too
```

#### Stack traceback and/or browser JavaScript console output
If I interrupt the kernel during the hang I got the following. It seems it's waiting for some thread to finish indefinitely.

```python
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-4-621c3d83bc78> in <module>
----> 1 datashade(hv.Image(arr))

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/IPython/core/displayhook.py in __call__(self, result)
    260             self.start_displayhook()
    261             self.write_output_prompt()
--> 262             format_dict, md_dict = self.compute_format_data(result)
    263             self.update_user_ns(result)
    264             self.fill_exec_result(result)

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/IPython/core/displayhook.py in compute_format_data(self, result)
    149 
    150         """
--> 151         return self.shell.display_formatter.format(result)
    152 
    153     # This can be set to True by the write_output_prompt method in a subclass

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/IPython/core/formatters.py in format(self, obj, include, exclude)
    148             return {}, {}
    149 
--> 150         format_dict, md_dict = self.mimebundle_formatter(obj, include=include, exclude=exclude)
    151 
    152         if format_dict or md_dict:

<decorator-gen-12> in __call__(self, obj, include, exclude)

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/IPython/core/formatters.py in catch_format_error(method, self, *args, **kwargs)
    222     """show traceback on failed format call"""
    223     try:
--> 224         r = method(self, *args, **kwargs)
    225     except NotImplementedError:
    226         # don't warn on NotImplementedErrors

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/core/dimension.py in _repr_mimebundle_(self, include, exclude)
   1292         combined and returned.
   1293         """
-> 1294         return Store.render(self)
   1295 
   1296 

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/core/options.py in render(cls, obj)
   1366         data, metadata = {}, {}
   1367         for hook in hooks:
-> 1368             ret = hook(obj)
   1369             if ret is None:
   1370                 continue

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/ipython/display_hooks.py in pprint_display(obj)
    279     if not ip.display_formatter.formatters['text/plain'].pprint:
    280         return None
--> 281     return display(obj, raw_output=True)
    282 
    283 

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/ipython/display_hooks.py in display(obj, raw_output, **kwargs)
    255     elif isinstance(obj, (HoloMap, DynamicMap)):
    256         with option_state(obj):
--> 257             output = map_display(obj)
    258     elif isinstance(obj, Plot):
    259         output = render(obj)

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/ipython/display_hooks.py in wrapped(element)
    144         try:
    145             max_frames = OutputSettings.options['max_frames']
--> 146             mimebundle = fn(element, max_frames=max_frames)
    147             if mimebundle is None:
    148                 return {}, {}

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/ipython/display_hooks.py in map_display(vmap, max_frames)
    204         return None
    205 
--> 206     return render(vmap)
    207 
    208 

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/ipython/display_hooks.py in render(obj, **kwargs)
     66         renderer = renderer.instance(fig='png')
     67 
---> 68     return renderer.components(obj, **kwargs)
     69 
     70 

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/plotting/bokeh/renderer.py in components(self, obj, fmt, comm, **kwargs)
    248         # Bokeh has to handle comms directly in <0.12.15
    249         comm = False if bokeh_version < '0.12.15' else comm
--> 250         return super(BokehRenderer, self).components(obj,fmt, comm, **kwargs)
    251 
    252 

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/plotting/renderer.py in components(self, obj, fmt, comm, **kwargs)
    319             plot = obj
    320         else:
--> 321             plot, fmt = self._validate(obj, fmt)
    322 
    323         data, metadata = {}, {}

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/plotting/renderer.py in _validate(self, obj, fmt, **kwargs)
    218         if isinstance(obj, tuple(self.widgets.values())):
    219             return obj, 'html'
--> 220         plot = self.get_plot(obj, renderer=self, **kwargs)
    221 
    222         fig_formats = self.mode_formats['fig'][self.mode]

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/plotting/bokeh/renderer.py in get_plot(self_or_cls, obj, doc, renderer, **kwargs)
    133             curdoc().theme = self_or_cls.theme
    134         doc.theme = self_or_cls.theme
--> 135         plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer, **kwargs)
    136         plot.document = doc
    137         return plot

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/plotting/renderer.py in get_plot(self_or_cls, obj, renderer, **kwargs)
    184 
    185         # Initialize DynamicMaps with first data item
--> 186         initialize_dynamic(obj)
    187 
    188         if not isinstance(obj, Plot):

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/plotting/util.py in initialize_dynamic(obj)
    248             continue
    249         if not len(dmap):
--> 250             dmap[dmap._initial_key()]
    251 
    252 

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/core/spaces.py in __getitem__(self, key)
   1325         # Not a cross product and nothing cached so compute element.
   1326         if cache is not None: return cache
-> 1327         val = self._execute_callback(*tuple_key)
   1328         if data_slice:
   1329             val = self._dataslice(val, data_slice)

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/core/spaces.py in _execute_callback(self, *args)
   1098 
   1099         with dynamicmap_memoization(self.callback, self.streams):
-> 1100             retval = self.callback(*args, **kwargs)
   1101         return self._style(retval)
   1102 

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/core/spaces.py in __call__(self, *args, **kwargs)
    732 
    733         try:
--> 734             ret = self.callable(*args, **kwargs)
    735         except KeyError:
    736             # KeyError is caught separately because it is used to signal

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/util/__init__.py in dynamic_operation(*key, **kwargs)
    937                 kwargs = dict(util.resolve_dependent_kwargs(self.p.kwargs), **kwargs)
    938                 obj = map_obj[key] if isinstance(map_obj, HoloMap) else map_obj
--> 939                 return self._process(obj, key, kwargs)
    940         else:
    941             def dynamic_operation(*key, **kwargs):

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/util/__init__.py in _process(self, element, key, kwargs)
    924         elif isinstance(self.p.operation, Operation):
    925             kwargs = {k: v for k, v in kwargs.items() if k in self.p.operation.param}
--> 926             return self.p.operation.process_element(element, key, **kwargs)
    927         else:
    928             return self.p.operation(element, **kwargs)

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/core/operation.py in process_element(self, element, key, **params)
    141         """
    142         self.p = param.ParamOverrides(self, params)
--> 143         return self._apply(element, key)
    144 
    145 

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/core/operation.py in _apply(self, element, key)
    119         for hook in self._preprocess_hooks:
    120             kwargs.update(hook(self, element))
--> 121         ret = self._process(element, key)
    122         for hook in self._postprocess_hooks:
    123             ret = hook(self, ret, **kwargs)

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/operation/datashader.py in _process(self, element, key)
   1132     def _process(self, element, key=None):
   1133         agg = rasterize._process(self, element, key)
-> 1134         shaded = shade._process(self, agg, key)
   1135         return shaded
   1136 

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/holoviews/operation/datashader.py in _process(self, element, key)
   1108         with warnings.catch_warnings():
   1109             warnings.filterwarnings('ignore', r'invalid value encountered in true_divide')
-> 1110             if np.isnan(array.data).all():
   1111                 arr = np.zeros(array.data.shape, dtype=np.uint32)
   1112                 img = array.copy()

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/dask/array/core.py in __bool__(self)
   1434             )
   1435         else:
-> 1436             return bool(self.compute())
   1437 
   1438     __nonzero__ = __bool__  # python 2

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    164         dask.base.compute
    165         """
--> 166         (result,) = compute(self, traverse=False, **kwargs)
    167         return result
    168 

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    435     keys = [x.__dask_keys__() for x in collections]
    436     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 437     results = schedule(dsk, keys, **kwargs)
    438     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    439 

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     74                 pools[thread][num_workers] = pool
     75 
---> 76     results = get_async(
     77         pool.apply_async,
     78         len(pool._pool),

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    473             # Main loop, wait on tasks to finish, insert new ones
    474             while state["waiting"] or state["ready"] or state["running"]:
--> 475                 key, res_info, failed = queue_get(queue)
    476                 if failed:
    477                     exc, tb = loads(res_info)

/opt/miniconda3/envs/minian/lib/python3.8/site-packages/dask/local.py in queue_get(q)
    131 
    132     def queue_get(q):
--> 133         return q.get()
    134 
    135 

/opt/miniconda3/envs/minian/lib/python3.8/queue.py in get(self, block, timeout)
    168             elif timeout is None:
    169                 while not self._qsize():
--> 170                     self.not_empty.wait()
    171             elif timeout < 0:
    172                 raise ValueError("'timeout' must be a non-negative number")

/opt/miniconda3/envs/minian/lib/python3.8/threading.py in wait(self, timeout)
    300         try:    # restore state no matter what (e.g., KeyboardInterrupt)
    301             if timeout is None:
--> 302                 waiter.acquire()
    303                 gotit = True
    304             else:

KeyboardInterrupt: 
```

**Comment by philippjfr** [comment] 2020-03-30 13:52
I believe this is an interference between numba and dask threads locking each other up. As far as I understand it would be resolved by https://github.com/conda-forge/numba-feedstock/issues/43

**Comment by philippjfr** [comment] 2020-09-02 01:05
Cannot reproduce anymore, please reopen if it persists.

**Closed by philippjfr** 2020-09-02 01:05 UTC
