### ISSUE TITLE
BoxEdit Example: `WARNING:param.RectanglesPlot00829: Tool of type 'box_edit' could not be found and could not be activated by default.`

### ISSUE THREAD

**Issue by turbotimon** [holoviz/holoviews#5770] opened 2023-06-20 09:40 UTC
#### ALL software version info
> Name: holoviews
Version: 1.16.2
Name: bokeh
Version: 3.1.1
Name: jupyter-bokeh
Version: 3.0.7

#### Description of expected behavior and the observed behavior

- On your [BoxEdit example](https://holoviews.org/reference/streams/bokeh/BoxEdit.html) a warning appears
- Also, i can therefore not interact (move, change, delete) with the rectangles.
- Same errors appears when i download the notebook and run it locally
- Similar to issue https://github.com/holoviz/holoviews/issues/5614 but it seams not yet solved

> WARNING:param.RectanglesPlot01428: Tool of type 'box_edit' could not be found and could not be activated by default.
![image](https://github.com/holoviz/holoviews/assets/57718207/7245aaa8-3f1e-4aae-8eb3-d95feea84a1d)

#### Complete, minimal, self-contained example code that reproduces the issue

- see https://holoviews.org/reference/streams/bokeh/BoxEdit.html#properties (or download notebook and run locally)

**Comment by Hoxbro** [comment] 2023-06-21 09:04
This is a duplicate of https://github.com/holoviz/holoviews/issues/5756.

**Closed by Hoxbro** 2023-06-21 09:04 UTC
