### ISSUE TITLE
Support datetime formatting in bokeh hover tools

### ISSUE THREAD

**Issue by thoth291** [holoviz/holoviews#1261] opened 2017-04-10 14:51 UTC
Here is what I have right now (installed all the packages for Python 3.6.1 a minute ago):
![image](https://cloud.githubusercontent.com/assets/2971670/24867348/848fb850-1dd2-11e7-9c0f-d8171b0b7e7a.png)

Please note that axis is rendered properly - it's just a hover tool who is missing the right rendering.

P.S. It's pretty typical `last mile` issue with `holoviews`: when you get your plot defined properly up to 95% but the last 5% makes you drop it and move to native bokeh, matplotlib struggling.

Thanks in Advance!

**Comment by philippjfr** [comment] 2017-04-10 15:46
I've now handled this correctly in #1263. That said there are various mechanisms to get around ``last mile`` issues, the simplest of which is to use ``finalize_hooks`` to modify the plot objects directly, e.g. to address this issue something like this would work:

```python
def fix_hover_date(plot, element):
    if 'hover' not in plot.handles:
        return
    xdim = element.kdims[0]
    hover = plot.handles['hover']
    source = plot.handles['source']
    hover.tooltips[0] = ('x', '@{x_dt}')
    source.data['x_dt'] = [xdim.pprint_value(v) for v in source.data['x']]

%%opts Curve [tools=['hover'] finalize_hooks=[fix_hover_date]]
hv.Curve((list(pd.date_range('2016-01-01', '2016-01-31')), range(31)))
```

**Comment by philippjfr** [comment] 2017-04-10 17:23
This has now been merged.

**Comment by bacalfa** [comment] 2018-03-14 14:16
I'm still having this issue.

![image](https://user-images.githubusercontent.com/1297074/37407218-84916298-276f-11e8-8197-a5bf20dd6418.png)

Here's the `dtypes` result:

```
Entry Time            datetime64[ns]
Frequency of Calls             int64
dtype: object
```

Package versions:
bokeh=0.12.14=py36_0
holoviews=1.9.4=py36_0

**Comment by bacalfa** [comment] 2018-03-15 00:11
This is weird... a small example worked fine:

![image](https://user-images.githubusercontent.com/1297074/37437465-cc9c7056-27c3-11e8-8865-1d99fe227351.png)

I have to figure out what's happening in the other case. Unfortunately, I can't share it. Any guesses?

**Comment by bacalfa** [comment] 2018-03-15 12:50
It seems it has to do with changing column/dimension names (?). Here's what's happening.

The following doesn't work as expected (dates aren't formatted properly in hover tool text):
```
df_resample= {}
df_resample_curves = []
for d in dlist:
    df_resample[d] = df[d].resample("15T", on="EntryTime").count()["Some Name"].reset_index()
    df_resample[d].columns = ["Entry Time", "Frequency of Calls"]
    df_resample_curves.append(hv.Curve(df_resample[d], kdims=["Entry Time"], vdims=["Frequency of Calls"]).relabel(d))
```
```
%%opts Overlay [legend_position="top"]
%%opts Curve [width=700 height=500 tools=["hover"]]
hv.Overlay(df_resample_curves)
```

If I don't change the column names, it works fine:
```
df_resample= {}
df_resample_curves = []
for d in dlist:
    df_resample[d] = df[d].resample("15T", on="EntryTime").count()["Some Name"].reset_index()
    df_resample_curves.append(hv.Curve(df_resample[d], kdims=["EntryTime"], vdims=["Some Name"]).relabel(d))
```
```
%%opts Overlay [legend_position="top"]
%%opts Curve [width=700 height=500 tools=["hover"]]
hv.Overlay(df_resample_curves)
```

Even if I do `.redim(EntryTime="Entry Time")`, it also messes up the date formatting. So something is going on when changing the name of the date dimension.

**Comment by philippjfr** [comment] 2018-03-15 13:01
Thanks for investigating that's very helpful! I think I have a good idea what it might be now.

**Comment by rsignell-usgs** [comment] 2018-10-26 11:36
@philippjfr, I'm hitting this same problem:
 
![date_label](https://user-images.githubusercontent.com/1872600/47563989-80894d80-d8f1-11e8-8b80-b193ad8e11fb.png)

Here's [the reproducible notebook that displays the problem](https://nbviewer.jupyter.org/gist/rsignell-usgs/dbdfdee053189658f7ac547ce407c99c
) just in case another example is useful.

**Comment by philippjfr** [comment] 2018-10-26 11:39
That's definitely useful, thanks!

**Comment by AnnaBernbaum** [comment] 2019-01-05 23:58
Was this issue ever resolved? I am still having DateTime Hovertool problems

**Comment by philippjfr** [comment] 2019-02-23 13:17
It's really hard to get a handle on what is still broken because none of the bug reports here include a reproducible example. I'll try to take a look but I'm not convinced I'll cover all the cases, so if you want your particular use case addressed please remember to add a bit of code that will let me reproduce the issue.

**Comment by philippjfr** [comment] 2019-02-23 15:09
The Raster/Image case is now handled, I can't currently reproduce any other issues. I'll reassign to 1.12 and if no new issues are reported by then I'll close due to non-reproducibility.

**Comment by BenPortner** [comment] 2019-08-06 14:30
I'm experiencing the same problem. A quick workaround seems to be redefinition of the tooltips:

`    tt = [
        ("date", "@date_column{F}"),
    ]`

does not render the output correctly, but using 

`    tt = [
        ("date", "@{date_column}"),
    ]`

will. That is because there seems to be an internal mechanism which produces an additonal column of the date string in the source and overwrites the tooltip (see holoviews.plotting.bokeh.element._postprocess_hover).

However, the main problem remains: Why does {%F} not produce the correct output?

**Comment by BenPortner** [comment] 2019-08-06 14:54
Okay I figured out why {%F} does not work at least in my case. I am using geoviews. In one of its functions the formatters are overwritten  (_postprocess_hover function of geoviews.plotting.bokeh.plot module)

**Comment by philippjfr** [comment] 2019-08-06 15:07
Thanks for finding the `{%F}` thing, I wasn't aware of it. Should be an easy thing to add now.

**Comment by BenPortner** [comment] 2019-08-06 19:16
Apart from the {%F} there is a whole range of other formatters for numbers and dates in bokeh. See
https://bokeh.pydata.org/en/latest/docs/reference/models/formatters.html 
I would be neat to find a flexible fix to make holoview support all of them!

**Comment by anderl80** [comment] 2019-09-03 13:37
I have problems with geoviews and timestamp tooltips, too. I built a dynamic panel with DynamicPlots based on gv.Points. The day is selectable in the date picker. Initially everything is fine and the hover tool shows formatted datetime. However if select another day with the date picker tool, then all datetime columns are shown in the hover tool as unix timestamps.

**Comment by philippjfr** [comment] 2020-03-05 11:12
It is still very difficult for me to reproduce problems here with reproducible examples.

**Comment by BenPortner** [comment] 2020-03-11 09:57
> It is still very difficult for me to reproduce problems here with reproducible examples.

@philippjfr 

Here is a minimum working example that reproduces the problem (in geoviews):

```
import geoviews as gv
import pandas as pd
from bokeh.models import HoverTool

d = dict(
    id=["A", "B", "C"],
    long=[-10, 0, 10],
    lat=[0, 0, 0],
    date=["2010-01-01", "2011-01-02", "2012-01-03"]
)
source = pd.DataFrame(d)
source["date"] = pd.to_datetime(source["date"])

gv.extension('bokeh')
tiles = gv.tile_sources.Wikipedia
points = gv.Points(source, ['long', 'lat'], ['id', 'date'])
fig = (tiles * points.opts(tools=[HoverTool(tooltips=[('date', '@date{F}')])]))
gv.renderer('bokeh').save(fig, "geoviews_min")
``` 


Expected output:
Three points along the equator. On hover, the date field should show dates in the format "YYYY-MM-DD". 

Output right now:
Points are positioned correctly but hover field shows random integer values.

**Comment by philippjfr** [comment] 2020-03-11 10:04
Thank you, much appreciated!

**Comment by philippjfr** [comment] 2020-03-23 20:14
@BenPortner That is not a HoloViews issue, the correct definition for date formatting would be:

```
fig = (tiles * points.opts(tools=[HoverTool(tooltips=[('date', '@{date}{%F}')], formatters={'@{date}': 'datetime'})]))
```

**Closed** 2020-03-23 21:43 UTC
Labels: bokeh, bug

**Comment by BenPortner** [comment] 2020-03-24 09:36
@philippjfr 
Sorry, the issue is not resolved for me.

My example with your correction does not work with Holoviews 1.12.7. The output is now a random percentage number. When updating to holoviews 1.13.0 (latest conda-forge build), the example does not run at all and throws an error:

`Traceback (most recent call last):
  File "C:\Users\user\programs\miniconda\envs\geo\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\panel\config.py", line 127, in set
    yield
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\panel\io\save.py", line 94, in save
    model = panel.get_root(doc, comm)
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\panel\viewable.py", line 528, in get_root
    root = self._get_model(doc, comm=comm)
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\panel\layout.py", line 136, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\panel\layout.py", line 126, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\panel\pane\holoviews.py", line 227, in _get_model
    plot = self._render(doc, comm, root)
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\panel\pane\holoviews.py", line 286, in _render
    return renderer.get_plot(self.object, **kwargs)
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\holoviews\plotting\bokeh\renderer.py", line 73, in get_plot
    plot = super(BokehRenderer, self_or_cls).get_plot(obj, doc, renderer, **kwargs)
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\holoviews\plotting\renderer.py", line 219, in get_plot
    **plot_opts)
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\geoviews\plotting\bokeh\plot.py", line 181, in __init__
    super(GeoOverlayPlot, self).__init__(element, **params)
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\geoviews\plotting\bokeh\plot.py", line 63, in __init__
    super(GeoPlot, self).__init__(element, **params)
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\holoviews\plotting\plot.py", line 1451, in __init__
    params['projection'] = self._get_projection(overlay)
  File "C:\Users\user\programs\miniconda\envs\geo\lib\site-packages\geoviews\plotting\plot.py", line 36, in _get_projection
    from_overlay = not all(p is None for p in opts[True]['projection'])
KeyError: 'projection'`

**Comment by philippjfr** [comment] 2020-03-24 11:01
I have to release a new version of GeoViews before that combination will work.

**Comment by ludwigVonKoopa** [comment] 2021-08-25 06:50
Hello, 

I don't know if you have seen it, but it seems thats with datetime64 dtype, holoviews operation break hover formatting (lon/lat projection, and datetime64 formating) : 

```python
import xarray as xr
import holoviews as hv
import geoviews as gv
print("xarray    : ", xr.__version__)
print("holoviews : ", hv.__version__)
print("geoviews  : ", gv.__version__)

gv.extension("bokeh")
```

<pre>
xarray    :  0.18.2
holoviews :  1.14.4
geoviews  :  1.9.1
</pre>

dataset creation : 
```python
dates = np.arange(np.datetime64("2003-01-01"), np.datetime64("2003-01-31"))


ds = xr.Dataset(
    data_vars=dict(
        ssh=(["time"], np.random.rand(dates.size)),
        lon=(["time"], np.arange(dates.size)),
        lat=(["time"], np.arange(dates.size)),
    ),
    coords=dict(
        time=(["time"], dates),
    ),
)
ds = ds.set_coords(["lon", "lat"])
ds
```


<pre>
<xarray.Dataset>
Dimensions:  (time: 30)
Coordinates:
    lon      (time) int64 0 1 2 3 4 5 6 7 8 9 ... 20 21 22 23 24 25 26 27 28 29
    lat      (time) int64 0 1 2 3 4 5 6 7 8 9 ... 20 21 22 23 24 25 26 27 28 29
  * time     (time) datetime64[ns] 2003-01-01 2003-01-02 ... 2003-01-30
Data variables:
    ssh      (time) float64 0.5383 0.6256 0.8142 0.133 ... 0.2735 0.3203 0.9386
</pre>


Plot : 

```python
from holoviews.operation import decimate

pts = gv.Points(
    (ds.lon, ds.lat, ds.ssh, ds.time), 
    kdims=["lon", "lat"], 
    vdims=["ssh", "time"]
).opts(tools=["hover"], size=8)

pts.opts(title="without decimate") + decimate(pts).opts(title="with decimate")
```

![github1](https://user-images.githubusercontent.com/49512274/130740064-f6418e9e-3dd4-4fcf-b27b-2620c94aab76.png)


link to another github issue created before : [Wrong hover values on hv.operation.decimate when data is np.datetime64](https://github.com/holoviz/holoviews/issues/4974)
link to original holoviz.discourse : [Wrong hover values on hv.operation.decimate when data is np.datetime64](https://discourse.holoviz.org/t/wrong-hover-values-on-hv-operation-decimate-when-data-is-np-datetime64/2420)

sorry to re-open this issue

**Comment by MarcSkovMadsen** [comment] 2021-08-25 07:47
Hi @ludwigVonKoopa 

Thanks for taking the time to contribute. Could you post this as a new issue please?

This post has been closed and can be overlooked. It makes it much easier for the contributors using the limited spare time to fix if a new issue is created.

You issue is well described though. A true "gift" to an open source project. Thanks.

**Comment by ludwigVonKoopa** [comment] 2021-08-25 07:50
Hi @MarcSkovMadsen 

I already have created an issue describing this problem (see #4974) but i'll edit it to make it simplier and easier to reproduce.

Thanks to your feedback
