### ISSUE TITLE
streams.PointDraw Python object is not linked to interactive plot

### ISSUE THREAD

**Issue by alexgleith** [holoviz/holoviews#5722] opened 2023-05-22 22:59 UTC
#### ALL software version info

* Python 3.11.3
* holoviews==1.16.0
* hvplot==0.8.3
* bokeh==2.4.3
* jupyter-bokeh==3.0.5

Tested in VS Code and using Jupyter Lab on a M1 Mac.

#### Description of expected behaviour and the observed behaviour

Running the [PointDraw example here](https://holoviews.org/reference/streams/bokeh/PointDraw.html), using simpler code below, I can draw points and see them update on the table. But if I run `point_stream.data` in a later cell, only the original points are shown.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
from holoviews import streams, opts
from holoviews.plotting.links import DataLink
hv.extension('bokeh')


data = ([0, 0.5, 1], [0, 0.5, 0], ['red', 'green', 'blue'])
points = hv.Points(data, vdims='color').redim.range(x=(-.1, 1.1), y=(-.1, 1.1))
point_stream = streams.PointDraw(data=points.columns(), num_objects=10, source=points, empty_value='black')

(points).opts(
    opts.Layout(merge_tools=False),
    opts.Points(active_tools=['point_draw'], color='color', height=400,
                size=10, tools=['hover'], width=400)
)
```

#### Stack traceback and/or browser JavaScript console output

Nothing is output on the JavaScript console and no stack trace is shown. 

#### Screenshots or screencasts of the bug in action

Note that there are six points added to the plot, and only the original three shown in the Python data object.

<img width="728" alt="image" src="https://github.com/holoviz/holoviews/assets/3445853/8525c54b-22d8-4bf3-a20c-9621fc92d140">

**Comment by Hoxbro** [comment] 2023-05-23 09:30
Also a problem with Bokeh 3. Though the problem is different, new dots will not appear on the plot but only in the data.

**Comment by Hoxbro** [comment] 2023-05-23 11:53
This is an upstream problem: https://github.com/bokeh/bokeh/issues/13155

**Comment by alexgleith** [comment] 2023-05-23 12:12
Is there a version of `bokeh` that it will work with? I'm not on Bokeh 3.

Also, I've tested in another environment and it's working... I can't work out which library might be causing the difference though. If you like, I can share the `pip freeze` from the two environments.

**Comment by Hoxbro** [comment] 2023-06-16 08:55
Holoviews 1.16.2 now has a workaround for this problem so I  will close this issue.

https://github.com/holoviz/holoviews/assets/19758978/d621a4f6-cd94-497b-b870-9db7df795046

![image](https://github.com/holoviz/holoviews/assets/19758978/c0cd7b86-ff1d-4337-9ae1-de5f25c36b18)

**Closed by Hoxbro** 2023-06-16 08:55 UTC
Labels: tag: backend: bokeh, upstream
