### ISSUE TITLE
link_selection(scatter + table) TypeError build_selection() got an unexpected keyword argument 'cache'

### ISSUE THREAD

**Issue by SandervandenOord** [holoviz/holoviews#4671] opened 2020-10-31 14:16 UTC
hv.__version__ = 1.13.5
holoviews @ git+https://github.com/pyviz/holoviews.git@45dca28bed3195d6b70209970a113a7cce961dbe

I was trying the link_selection of a scatter_plot + table as mentioned in this issue: https://github.com/holoviz/holoviews/issues/4505

This error happens when making a link_selection with a table:
`link(scatter+table)`

But now got the following error:
`TypeError: build_selection() got an unexpected keyword argument 'cache'`

```

TypeError                                 Traceback (most recent call last)
<ipython-input-6-9f58def70a40> in <module>
----> 1 link(scatter+table)

~/Datascience/Anaconda/anaconda3/envs/hv_new/lib/python3.7/site-packages/holoviews/selection.py in __call__(self, hvobj, **kwargs)
    142 
    143         # Perform transform
--> 144         return self._selection_transform(hvobj.clone())
    145 
    146     def _selection_transform(self, hvobj, operations=()):

~/Datascience/Anaconda/anaconda3/envs/hv_new/lib/python3.7/site-packages/holoviews/selection.py in _selection_transform(self, hvobj, operations)
    181         elif isinstance(hvobj, (Layout, Overlay, NdOverlay, GridSpace)):
    182             data = OrderedDict([(k, self._selection_transform(v, operations))
--> 183                                  for k, v in hvobj.items()])
    184             if isinstance(hvobj, NdOverlay):
    185                 def compose(*args, **kwargs):

~/Datascience/Anaconda/anaconda3/envs/hv_new/lib/python3.7/site-packages/holoviews/selection.py in <listcomp>(.0)
    181         elif isinstance(hvobj, (Layout, Overlay, NdOverlay, GridSpace)):
    182             data = OrderedDict([(k, self._selection_transform(v, operations))
--> 183                                  for k, v in hvobj.items()])
    184             if isinstance(hvobj, NdOverlay):
    185                 def compose(*args, **kwargs):

~/Datascience/Anaconda/anaconda3/envs/hv_new/lib/python3.7/site-packages/holoviews/selection.py in _selection_transform(self, hvobj, operations)
    176                 return chart.selection_display(element).build_selection(
    177                     self._selection_streams, element, operations,
--> 178                     self._selection_expr_streams.get(element, None), cache=self._cache
    179                 )
    180             return hvobj

TypeError: build_selection() got an unexpected keyword argument 'cache'
```

**Sample code:**
```
import pandas as pd
import holoviews as hv
from holoviews.selection import link_selections
hv.extension('bokeh')

data = {"x": [1,2,3,4,5], "y": [2,4,5,7,10]}
df = pd.DataFrame(data)
dataset = hv.Dataset(df)
dataset

bars = hv.Bars(dataset, "x", "y")
scatter = hv.Scatter(dataset, "x", "y")
table = hv.Table(dataset)

link = link_selections.instance()
link(scatter+table)
```

**Comment by marckassay** [comment] 2020-12-09 22:29
Fyi, I don't get this error when holoviews `v1.13.4` is used. So I assume something between that revision and `v1.13.5` is the cause.

**Comment by philippjfr** [comment] 2020-12-10 01:40
Thanks, we'll try to get a fix for this in asap.

**Closed** 2020-12-15 19:25 UTC
